domain: luzojeda.github.io
url: https://luzojeda.github.io
baseurl: /luzojeda/

title: 'Luz Ojeda'
author:
  name: 'Luz Ojeda'

plugins:
  - jekyll-multiple-languages-plugin

# Custom variables
github_url: 'https://github.com/lezojeda'
linkedin_url: 'https://www.linkedin.com/in/lezojeda/'

current_company: Southworks
current_company_url: https://www.southworks.com/

lang: en
languages: ['en', 'es']
exclude_from_localizations: ['javascript', 'images', 'css', 'assets']
defaultLang: en
languageNames:
  es: Español
  en: English
