baseurl: ''
url: ''

title: 'Luz Ojeda'
author:
  name: 'Luz Ojeda'

repository: luz-ojeda/luz-ojeda.github.io

plugins:
  - jekyll-multiple-languages-plugin

collections:
  - pictures

# Custom variables
github_url: 'https://github.com/luz-ojeda'
linkedin_url: 'https://www.linkedin.com/in/luz-ojeda/'
instagram_url: 'https://www.instagram.com/luzojeda._/'
resume_url: 'https://drive.google.com/file/d/13bN8bFh_Lsho5dHh2whhhsmH5kIsiq3A/view?usp=share_link'
backloggd_url: 'https://www.backloggd.com/u/synthopia/'
goodreads_url: 'https://www.goodreads.com/user/show/116528903-luz'
steam_url: 'https://steamcommunity.com/id/luzojeda/'

current_company: Southworks
current_company_url: https://www.southworks.com/

imagesurl: "/assets/images/"
thumbsurl: "/assets/images/"

# Multiple l.anguages plugin
languages: ['en', 'es']

exclude_from_localizations: ['javascript', 'images', 'css', 'assets']
