baseurl: ''
url: ''

title: 'Luz Ojeda'
author:
  name: 'Luz Ojeda'

repository: luz-ojeda/luz-ojeda.github.io

plugins:
  - jekyll-multiple-languages-plugin

collections:
  - pictures
  - microposts

# Custom variables
github_url: 'https://github.com/luz-ojeda'
linkedin_url: 'https://www.linkedin.com/in/luz-ojeda/'
instagram_url: 'https://www.instagram.com/synthopia_/'
resume_url: 'https://drive.google.com/file/d/1GwTzG-jrj2bpQS8-KuETgCWu5Dj_jhFu/view?usp=sharing'
backloggd_url: 'https://www.backloggd.com/u/eucariota/'
goodreads_url: 'https://www.goodreads.com/user/show/116528903-luz'
steam_url: 'https://steamcommunity.com/id/luzojeda/'
email: 'luzojeda@proton.me'

imagesurl: "/assets/images/"

# Multiple languages plugin
languages: ['en', 'es']

exclude_from_localizations: ['javascript', 'images', 'css', 'assets']
