baseurl: ''
url: ''

title: 'Luz Ojeda'
author:
  name: 'Luz Ojeda'

repository: luz-ojeda/luz-ojeda.github.io

plugins:
  - jekyll-multiple-languages-plugin

# Custom variables
github_url: 'https://github.com/luz-ojeda'
linkedin_url: 'https://www.linkedin.com/in/luz-ojeda/'
instagram_url: 'https://www.instagram.com/luzojeda._/'

current_company: Southworks
current_company_url: https://www.southworks.com/

languages: ['en', 'es']

exclude_from_localizations: ['javascript', 'images', 'css', 'assets']

imagesurl: "/assets/images/"
thumbsurl: "/assets/images/"
